### ISSUE TITLE
Jinx - The Bot Price Verifier

### ISSUE THREAD

**Issue by JinxArcane235** [JinxArcane235/jinx#1]
# Motivation
The project requires real-time tracking of the Solana (SOL) price and key technical indicators to make informed decisions.

# Proposal
Implement a feature to:

* Monitor Solana Price: Fetch the current SOL price every 30 minutes.
* Analyze RSI (Relative Strength Index): Extract the RSI value from the 4-hour chart available on [TradingView](https://www.tradingview.com/chart/?symbol=COINBASE%3ASOLUSD).

# Reference
The RSI indicator and price information should be sourced from the TradingView chart:

<img width="1446" alt="image" src="https://github.com/user-attachments/assets/c865eda7-538a-4fd7-98b8-cf37098a850b">

**Comment by rusgot** [comment]
![sol-tradingview-with-relative-strength-index](https://github.com/user-attachments/assets/3eb7c36e-33ed-4c50-98e5-ba6f651694e6)
This is the result
and you can try this on your side.
I invited you.

**Comment by rusgot** [comment]
https://github.com/rusgot/Sol-price-tradingview-relative-strength-index/settings/access
This is link

**Comment by LamsyA** [comment]
#12 
- Implement real-time Solana price tracking using CoinGecko's public API
- Add RSI calculation with 14-period window
- Implement structured logging with Winston
- Add graceful shutdown handling

**Comment by uwemdev** [comment]
https://github.com/uwemdev/jinx/tree/main

Let me know if you need a GUI for it.
